Don't check for nova useablity when we use glance
We are only using glance and we are only passing in the glance endpoint,
so this nova check will always fail. Instead check for glance usability.

Change-Id: I78a83462ac9424afc84fef797c94fea6e531e78d
Fixes-bug: #1316290

diff --git a/contrib/lp-cedarish/vm-slug/build-app b/contrib/lp-cedarish/vm-slug/build-app
--- a/contrib/lp-cedarish/vm-slug/build-app
+++ b/contrib/lp-cedarish/vm-slug/build-app
@@ -19,10 +19,10 @@ function check_os_credentials () {
   fi
 }
 
-function check_nova_access () {
-  nova list 2> /dev/null > /dev/null
+function check_glance_access () {
+  glance index 2> /dev/null > /dev/null
   if [ $? != 0 ]; then
-    echo "Cannot talk to Nova. Check your OpenStack credentials." >&2
+    echo "Cannot talk to Glance. Check your OpenStack credentials." >&2
     exit 1
   fi
 }
@@ -108,7 +108,7 @@ function main () {
 
   check_docker
   check_os_credentials
-  check_nova_access
+  check_glance_access
   build_app $GIT_URL $APP_DIR
   inject_app_into_image $APP_DIR
   upload_image_to_glance $APP $APP_DIR
